import { CountryTradingData } from "@/type/interface";
import { NextResponse } from "next/server";

type ContinentRecord = {
  continentName: string;
  percentageValue: number;
  countriesData: CountryTradingData[];
};

export async function GET(req: Request) {
  const continentsData: ContinentRecord[] = [
    {
      continentName: 'Asia',
      percentageValue: 91.16,
      countriesData: [
        {
          countryName: 'China',
          shipments: 280430,
          countryCode: 'CN',
          proportion: 68.23,
          weight: 31442,
          teu: 24,
          value: undefined,
        },
        {
          countryName: 'India',
          shipments: 62154,
          countryCode: 'IN',
          proportion: 15.12,
          weight: 29502,
          teu: 16,
          value: undefined,
        },
        {
          countryName: 'Bangladesh',
          shipments: 17549,
          countryCode: 'BD',
          proportion: 4.27,
          weight: 18204,
          teu: 10,
          value: undefined,
        },
        {
          countryName: 'Pakistan',
          shipments: 10614,
          countryCode: 'PK',
          proportion: 2.58,
          weight: 12249,
          teu: 9,
          value: undefined,
        },
        {
          countryName: 'Cambodia',
          shipments: 8051,
          countryCode: 'KH',
          proportion: 1.96,
          weight: 10942,
          teu: 8,
          value: undefined,
        },
      ],
    },
    {
      continentName: 'Europe',
      percentageValue: 2.62,
      countriesData: [
        {
          countryName: 'Norway', 
          shipments: 7632,
          countryCode: "NO",
          proportion: 3.33,
          weight: 1109,
          teu: 10,
          value: undefined,
        },
        {
          countryName: 'Romania', 
          shipments: 2290,
          countryCode: "RO",
          proportion: 4.12,
          weight: 3121,
          teu: 12,
          value: undefined,
        },
        {
          countryName: 'Italy', 
          shipments: 1692,
          countryCode: "IT",
          proportion: 10.12,
          weight: 1967,
          teu: 1,
          value: undefined,
        },
        {
          countryName: 'Croatia', 
          shipments: 696,
          countryCode: "HR",
          proportion: 2.22,
          weight: 234,
          teu: 1,
          value: undefined,
        },
        {
          countryName: 'Hungary', 
          shipments: 513,
          countryCode: "HU",
          proportion: 2.09,
          weight: 190,
          teu: 3,
          value: undefined,
        },
      ],
    },
    {
      continentName: 'South America',
      percentageValue: 2.85,
      countriesData: [
        {
          countryName: 'Chile', 
          shipments: 7545,
          countryCode: "CL",
          proportion: 8.06,
          weight: 6568,
          teu: 24,
          value: undefined,
        },
        {
          countryName: 'Peru', 
          shipments: 1689,
          countryCode: "PE",
          proportion: 7.78,
          weight: 1560,
          teu: 19,
          value: undefined,
        },
        {
          countryName: 'Colombia', 
          shipments: 1401,
          countryCode: "CO",
          proportion: 11.12,
          weight: 992,
          teu: 16,
          value: undefined,
        },
        {
          countryName: 'Ecuador', 
          shipments: 663,
          countryCode: "EC",
          proportion: 9.22,
          weight: 540,
          teu: 5,
          value: undefined,
        },
        {
          countryName: 'Brazil', 
          shipments: 433,
          countryCode: "BR",
          proportion: 4.55,
          weight: 289,
          teu: 24,
          value: undefined,
        },
      ],
    },
    {
      continentName: 'North America',
      percentageValue: 1.47,
      countriesData: [
        {
          countryName: 'Guatemala', 
          shipments: 2155,
          countryCode: "GT",
          proportion: 13.12,
          weight: 2118,
          teu: 8,
          value: undefined,
        },
        {
          countryName: 'Honduras', 
          shipments: 1910,
          countryCode: "HN",
          proportion: 9.09,
          weight: 1596,
          teu: 15,
          value: undefined,
        },
        {
          countryName: 'Dominican',
          shipments: 1866,
          countryCode: "DO",
          proportion: 6.09,
          weight: 1705,
          teu: 11,
          value: undefined,
        },
        {
          countryName: 'Nicarague', 
          shipments: 1089,
          countryCode: "NI",
          proportion: 3.09,
          weight: 787,
          teu: 7,
          value: undefined,
        },
        {
          countryName: 'Haiti', 
          shipments: 756,
          countryCode: "HT",
          proportion: 2.78,
          weight: 575,
          teu: 12,
          value: undefined,
        },
      ],
    },
    {
      continentName: 'Africa',
      percentageValue: 0.89,
      countriesData: [
        {
          countryName: 'Nigeria', 
          shipments: 1863,
          countryCode: "NG",
          proportion: 6.12,
          weight: 1309,
          teu: 12,
          value: undefined,
        },
        {
          countryName: 'Lesotho', 
          shipments: 812,
          countryCode: "LS",
          proportion: 8.88,
          weight: 665,
          teu: 6,
          value: undefined,
        },
        {
          countryName: 'South Africa', 
          shipments: 766,
          countryCode: "ZA",
          proportion: 4.67,
          weight: 370,
          teu: 3,
          value: undefined,
        },
        {
          countryName: 'Morocco', 
          shipments: 146,
          countryCode: "MA",
          proportion: 1.01,
          weight: 85,
          teu: 2,
          value: undefined,
        },
        {
          countryName: 'Namibia', 
          shipments: 88,
          countryCode: "NA",
          proportion: 1.02,
          weight: 123,
          teu: 6,
          value: undefined,
        },
      ],
    },
  ];

  return NextResponse.json(continentsData);
}
